### PR TITLE
Some sites may note have search, and therefore, no search URL. I've a…

### PR DESCRIPTION
**Pull request by FlipperPA**
…ccounted for that with this commit.

### CODE REVIEW

**Comment by alexgleason** [comment]
Thanks Tim! I added you as a collaborator. Do you have an account on PyPi? I can add you there, too.

**Comment by FlipperPA** [comment]
I'm FlipperPA over there as well. Thanks a bunch, Alex! Funny that I was thinking that this would be a neat thing for Wagtail, Google'd, and surprise surprise, you'd already done it!

**Comment by alexgleason** [comment]
Awesome! Thanks for contributing. I also added you as an owner on PyPi so feel free to push updates as you please.

**Comment by FlipperPA** [comment]
Thanks, I've pushed update 1.1.5 (MANIFEST.in needed an update as well, to include README.md).

**Comment by alexgleason** [comment]
Awesome! Thanks!

**Pull request merged**
